### ISSUE TITLE
serialconnect is not working ("Device is not reachable.")

### ISSUE THREAD

**Issue by simplyshakoor** [Carglglz/jupyter_upydevice_kernel#1]
I'm trying to connect to my ESP32 but it's not working. I can connect through %websocketconnect but serial connect is not working. When I try with a different kernel I can connect without any problem.

**Comment by Carglglz** [comment]
Hi, I can connect with: 
```
%serialconnect /dev/tty.SLAB_USBtoUART

** Serial connected **

/dev/tty.SLAB_USBtoUART

MicroPython v1.12-63-g1c849d63a on 2020-01-14; ESP32 module with ESP32
Type "help()" for more information.
INFO:micropython-upydevice:Device esp32 connected in /dev/tty.SLAB_USBtoUART 
```
So what is the name of the serial port and what's your OS ?

To test connectivity to a serial device there is this method  `self.is_reachable()`:

```
def is_reachable(self):
        if self.serial.writable() and self.serial_port in glob.glob('/dev/*'):
            return True
        else:
            return False
```
Which tests if the serial is writable and if the serial port exists.
So one of this two is failing.

If you are using Windows then I will need to change this.
Can you test this in python?:
```
>>> import serial.tools.list_ports
>>> [p.device for p in serial.tools.list_ports.comports()]
['/dev/cu.MALS', '/dev/cu.SOC', '/dev/cu.Bluetooth-Incoming-Port', '/dev/cu.SLAB_USBtoUART']

```
And see if the serial port is in the result?

**Comment by simplyshakoor** [comment]
I'm using windows 10.
```
 import serial.tools.list_ports
 [p.device for p in serial.tools.list_ports.comports()]
```

>`['COM5']`

But when I try `%serialconnect COM5 115200`
I'm getting 

> `Device not reachable`

**Comment by Carglglz** [comment]
Thanks, @simplyshakoor 
I uploaded a new version of upydevice and this kernel with these changes Carglglz@75da0141aac0ba0d03de823897b85742443086e7,  Carglglz/upydevice@fb0b226a35dd869e4f0c045920a8d0bec95061dd so do:

`pip install --upgrade jupyter-micropython-upydevice` or download from [releases](https://github.com/Carglglz/jupyter_upydevice_kernel/releases) and install.
This should be version 0.0.4 at least.

Then test again to see if it works or not and report if you have any problem.

**Comment by simplyshakoor** [comment]
Great now it's working. I'm able to use the serial connect as well.
